spring:
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/leetcode_stats
    username: ${DATABASE_PASSWORD:postgres}
    password: ${DATABSE_USERNAME:postgres}
    driverClassName: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
     # ddl-auto: validate
logging:
  level:
    root: info
app:
  codeDirectory: ${CODE_DIRECTORY:TO BE filled}
  notesDirectory: ${NOTES_DIRECTORY:TO BE FILLED}